### ISSUE TITLE
[BUG] Soketi not starting on nodejs major v20

### ISSUE THREAD

**Issue by ajaybhargav** [soketi/pws#1025]
**Description**
Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

This issue came after updating nodejs to v20

**Reproduction steps**
Update nodejs to latest LTS

**Expected behavior**
soketi should work

**Environment**
- Soketi version (i.e. 1.3.0): 1.6.0
- Adapter (local, redis): redis
- App Manager (array, mysql, postgres, dynamodb) : mysql
- Queue (sqs, redis, sync): redis
- Cache Managers (memory, redis): memory

**Additional context**
I think uws need to upgrade to latest version to support nodejs v20. Please provide a release.

**Comment by Diddyy** [comment]
I believe that the required uWebSockets need updating on Soketi.
I have Node.js v21 and cannot install due to uWS.js only supporting Node.js 14,16 and 18.

**Comment by neoteknic** [comment]
Same problem, have to rollback to 18 LTS.
Need to upgrade the uWS dependency.

**Comment by whitespacecode** [comment]
Same here. Node is at v20.10.0 LTS.
The docs are not representative -> (Node.js LTS (14.x, 16.x, so on))
This should be changed at least to show what the max node version should be

**Comment by Akhmami** [comment]
hi, is there any way to use node v20 LTS?

**Comment by ln8711** [comment]
bump!
uWebSockets.js supports node.js 20 since Oct 2023 already
https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.33.0

UPDATE:
PR here already: https://github.com/soketi/soketi/pull/1074

UPDATE 2:
To make it works, build it locally:

    Clone the project
    Edit package.json with "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.37.0"
    Run:
        npm install uWebSockets.js
        npm run build
    Start the server with:
        ./bin/server.js start
    

And happy holidays!

**Comment by OliverWich** [comment]
Bump again, can #1074 please get merged?
Node 18 has already reached the end of its official support a while ago and is only hanging on by a thread with maintenance releases.

**Comment by Fsmash** [comment]
Also bumping. I'll try running tests myself here soon to see if anything broke but so far after using soketi for 5 months with this updated uWebSockets I have not run into any issues.

**Comment by tobimori** [comment]
Bumping again; desperately need this :(

**Comment by wsamoht** [comment]
Just ran into this upgrading my local dev VM to Ubuntu 22.04.3. I ended up using NVM to install Node 18 and then added `/home/vagrant/.nvm/versions/node/v18.20.2/bin` to be added in the `PATH` env variable to my Supervisord config which runs Soketi.

**Comment by Lemmings19** [comment]
To expand on the comment above:
- [Install Node Version Manager](https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating) ("nvm"): `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`
- `. ~/bashrc` to apply some path stuff the installer added.
- `nvm` to check it is working.
- `nvm install 18`
- Modify the Supervisord config in `/etc/supervisor/conf.d/my-workers.conf` for running soketi to: `/home/vagrant/.nvm/versions/node/v18.20.2/bin/node /usr/bin/soketi start --config=/var/www/my-project/soketi.json` (`--config` flag is optional; it's just what I already had)

**Comment by renchris** [comment]
@rennokki would we please get https://github.com/soketi/soketi/pull/1074 reviewed to resolve and close this issue?

**Comment by whitespacecode** [comment]
This is driving me crazy.. Even with a fresh nvm/node/npm install i can't get soketi to work.
```cmd
C:\Windows\System32>soketi -v
C:\Users\Whitespace\AppData\Roaming\nvm\v18.19.1\node_modules\@soketi\soketi\node_modules\uWebSockets.js\uws.js:22
                throw new Error('This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).\n\n' + e.toString());
                ^

Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: error: 126\\?\C:\Users\Whitespace\AppData\Roaming\nvm\v18.19.1\node_modules\@soketi\soketi\node_modules\uWebSockets.js\uws_win32_x64_108.node
    at C:\Users\Whitespace\AppData\Roaming\nvm\v18.19.1\node_modules\@soketi\soketi\node_modules\uWebSockets.js\uws.js:22:9
    at Object.<anonymous> (C:\Users\Whitespace\AppData\Roaming\nvm\v18.19.1\node_modules\@soketi\soketi\node_modules\uWebSockets.js\uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (C:\Users\Whitespace\AppData\Roaming\nvm\v18.19.1\node_modules\@soketi\soketi\dist\server.js:18:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)

Node.js v18.19.1
```

**Comment by SDrinkwater** [comment]
@rennokki Is this project still actively maintained? From the looks of the latest commits, nothing that actually affects the project has been changed in ~9 months.

This issue is still tagged with the `triage` status after being open for ~7 months and the https://github.com/soketi/soketi/pull/1074 PR raised ~6 months ago has had no input from you, the sole core contributor (?).

Would be great to clear this up, so that we can know whether or not this project should be skipped entirely when considering options in this space.

**Comment by OliverWich** [comment]
Exactly our feeling as well.

I hate to put pressure on FOSS developers, but if there is a package that is awesome and used by many (aka. this one as there does not seem to be any good alternative for a pusher-compatible and easily self hosted websocket server), please at least annotate it in your README if there are limited capabilities or a maintenance dry spell so that users can either avoid it (which would be sad since we do very much like this project) or help with the maintenance.

Being left hanging is the worst, especially as your users have already started to work on a fix that just needs approval.

At least some communication whats going on would be greatly appreciated @rennokki!

**Comment by wsamoht** [comment]
If you are a Laravel user, they released a 1st Party WebSocket server - https://reverb.laravel.com. I'll be switching to it in the near future. It doesn't look like it is as feature rich, like no webhook support (at least yet). I think it supports API calls to get active channels and such though not documented (need to look into this further).

It utilizes the Pusher protocol so could probably be utilized if you aren't using Laravel.

**Comment by tobimori** [comment]
I know Reverb and actually use PHP for my project, but not Laravel. Do you know if there's anything that supports running Reverb without a Laravel project? Last time, but that was after the release, I havent' found anything.

**Comment by wsamoht** [comment]
I am not sure. I am personally going to install it into a fresh Laravel project so it's separate from my main Laravel app. Laravel 11 simplified the initial project structure so it's less overwhelming for newcomers :) If you did this, then you could also use Laravel Pulse to monitor your Reverb server.

**Comment by jskorlol** [comment]
In Laravel Reverb, it's difficult to accommodate a large number of users. It would be great if Soketi could support Node 20 and 22. Is there still no update on this?

**Comment by rahulhaque** [comment]
Have a look here in my [fork](https://github.com/rahulhaque/soketi). Running Node.js 22. To run -
```bash
# Clone the repo
git clone https://github.com/rahulhaque/soketi.git

# Install dependencies
npm install

# Build the server
npm run build

# Run the server
node bin/server.js start
```

**Comment by ajaybhargav** [comment]
after much thought and problems, Moved to Laravel Reverb.

**Comment by wsamoht** [comment]
> after much thought and problems, Moved to Laravel Reverb.

@ajaybhargav can you share your setup?

- Are you running it independently in its own Laravel app or in an existing Laravel app?
- How many concurrent connections do you have?
- Encounter any issues along the way switching or pretty much a drop-in replacement?

**Comment by ajaybhargav** [comment]
@wsamoht sure.

1. I was running soketi in Laravel application, which required a three way data communication between server, browser and a TCP server, not a usual setup though. But server <-> browser is common.
2. Not too many connections, but message rate is higher as data is coming from a machine.
3. Reverb here is a drop-in replacement with minor changes. Webhooks are much easier in reverb as you get Laravel Event Notification, all you have to do is just add a listener. it took me half day to understand this as it is not documented anywhere. So had to dig in source.

**Comment by craigrileyuk** [comment]
@rennokki – Any chance of getting this added as well as node v22 support now? Thanks.
