### ISSUE TITLE
[REQUEST] Force Dockerfile.debian to VERSION 16

### ISSUE THREAD

**Issue by xdestiny** [soketi/pws#1028]
**Is your feature request related to a problem? Please describe.**
Of course it happened during the project build for the Soketi container we use when Node changed their LTS version to 20. The current version of uWS.js used in this project doesn't support Node 20 yet. 

**Describe the solution you'd like**
The quick fix would be to force the Dockerfile.debian VERSION argument to 18 instead of lts, or to 16 as is done in the Alpine container.

**Describe alternatives you've considered**
Otherwise, update to a uWS.js version that supports Node 20.

**Additional context**
This is the error you would see on container start, for search and information purposes:

```
/app/node_modules/uWebSockets.js/uws.js:22
          throw new Error('This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).\n\n' + e.toString());
         ^

Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
 
Error: Cannot find module './uws_linux_arm64_115.node'
Require stack:
- /app/node_modules/uWebSockets.js/uws.js
- /app/dist/server.js
- /app/dist/index.js
- /app/dist/cli/cli.js
- /app/dist/cli/index.js
- /app/bin/server.js
    at /app/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/app/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/app/dist/server.js:18:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.9.0
```

**Comment by MaruanBO** [comment]
As you have already considered you can update to v20. Add this to your package.json:   `"uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.37.0"`, then install it `npm install uWebSockets.js` and finally you need to **build your assets** and run the **server.js**

Ref: https://github.com/soketi/soketi/pull/1074
