### ISSUE TITLE
[BUG] queue redis driver

### ISSUE THREAD

**Issue by chicagomg** [soketi/pws#1058]
### when enable driver redis I get an error

```
/app/dist/queues/redis-queue-driver.js:39
                    prefix: this.server.options.database.redis.keyPrefix.replace(/:$/, ''),
                                                                         ^
TypeError: Cannot read properties of undefined (reading 'replace')
    at /app/dist/queues/redis-queue-driver.js:39:74
    at new Promise (<anonymous>)
    at RedisQueueDriver.processQueue (/app/dist/queues/redis-queue-driver.js:22:16)
    at Queue.processQueue (/app/dist/queues/queue.js:28:28)
    at new WebhookSender (/app/dist/webhook-sender.js:113:33)
    at /app/dist/server.js:370:34
    at new Promise (<anonymous>)
    at Server.setWebhookSender (/app/dist/server.js:369:16)
    at Server.initializeDrivers (/app/dist/server.js:330:18)
    at /app/dist/server.js:230:18
```

**Comment by chicagomg** [comment]
Right Config
```json
"database": {
    "redis": {
      "host": "redis",
      "port": 6379,
      "db": 0,
      "username": null,
      "password": null,
      "clusterNodes": [],
      "keyPrefix": "myPrefix:"
    }
  }
```
