### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by ahmadyousefdev** [soketi/pws#1121]
Hello, I'm trying to use soketi with Laravel and valet,

the problem is happening when trying to generate a private broadcast event,

after sending the notification I get this error:
```
}
   [Sat Mar 09 2024 03:06:52 GMT+0300 (GMT+03:00)] ⚡ HTTP Payload received
{
  name: 'receivedNotice',
  data: '{"message":"\\u0645\\u0631\\u062d\\u0628\\u064b\\u0627 ....","values":{"SITE_URL":"http:\\/\\/test.frontendsite.test\\/","URL":"http:\\/\\/test.frontendsite.test\\/"}}',
  channel: 'private-tenant-123123.users.104'
}
  process uncaughtException
{
  err: TypeError: Cannot read properties of undefined (reading 'includes')
      at /usr/local/lib/node_modules/@soketi/soketi/dist/app.js:35:91
      at Array.filter (<anonymous>)
      at new App (/usr/local/lib/node_modules/@soketi/soketi/dist/app.js:35:53)
      at /usr/local/lib/node_modules/@soketi/soketi/dist/app-managers/array-app-manager.js:16:25
      at new Promise (<anonymous>)
      at ArrayAppManager.findById (/usr/local/lib/node_modules/@soketi/soketi/dist/app-managers/array-app-manager.js:13:16)
      at AppManager.findById (/usr/local/lib/node_modules/@soketi/soketi/dist/app-managers/app-manager.js:31:32)
      at HttpHandler.appMiddleware (/usr/local/lib/node_modules/@soketi/soketi/dist/http-handler.js:364:39)
      at nextTask (/usr/local/lib/node_modules/@soketi/soketi/node_modules/async/dist/async.js:5791:13)
      at next (/usr/local/lib/node_modules/@soketi/soketi/node_modules/async/dist/async.js:5799:13),
  origin: 'unhandledRejection'
}
```
then the connection stops
```
 🚫 New users cannot connect to this instance anymore. Preparing for signaling...
  ⚡ The server is closing and signaling the existing connections to terminate.
   [Sat Mar 09 2024 03:06:52 GMT+0300 (GMT+03:00)] ⚡ All sockets were closed. Now closing the server.
```
here is my broadcasting configuration:
```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY', 'app-key'),
            'secret' => env('PUSHER_APP_SECRET', 'app-secret'),
            'app_id' => env('PUSHER_APP_ID', 'app-id'),
            'options' => [
                'host' => 'backend.test',
                'port' => env('PUSHER_PORT', 6001),
                'cluster' => 'mt1',
                'scheme' => 'http',
                'encrypted' => true,
                'useTLS' => false,
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],
```
when setting scheme to 'https' i get this error in the laravel logs
```
Pusher error: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to backend.test:6001
```
when visiting backend.test:6001 on the browser it shows "ok".

I don't know what i'm doing wrong.

here is my Echo configuration:
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'app-key',
    cluster: 'mt1',
    wsHost: 'backend.test',
    wsPort: 6001,
    wssPort: 6001,
    forceTLS: false,
    encrypted: true,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
authorizer: (channel, options) => {
        return {
            authorize: (socketId, callback) => {
                console.log("Requested something")
                axios.get(window.api_url + 'broadcasting/auth', {
                    socket_id: socketId,
                    channel_name: channel.name
                })
                    .then(response => {
                        console.log(response)
                        callback(false, response);
                    })
                    .catch(error => {
                        callback(true, error);
                    });
            }
        };
    },
```

i'm running soketi with the config file like this `soketi start --config=/Users/myname/code/backend/config.json`, which has this content:
```
{
  "debug": true,
    "appManager.array.apps": [
      {
        "id": "app-id",
        "key": "app-key",
        "secret": "app-secret",
        "maxConnections": -1,
        "enableClientMessages": false,
        "enabled": true,
        "maxBackendEventsPerSecond": -1,
        "maxClientEventsPerSecond": -1,
        "maxReadRequestsPerSecond": -1,
        "webhooks": [
          {
            "url": "https://backend.test"
        }
        ],
        "ssl": [
          {
            "certPath" : "/Users/myname/.config/valet/Certificates/backend.test.crt",
            "keyPath": "/Users/myname/.config/valet/Certificates/backend.test.key",
            "passphrase": "",
            "caPath": ""
      
          }
        ]
      }
    ]
  }
```

the problem only happens with private channels, the public channels work well. is there a special wssPort other than 6001?

I just want to know what is my problem, I'd appreciate any help.

**Comment by ahmadyousefdev** [comment]
I think the problem is wss port is not being available in valet. ws port works with no problem, but if the sites and the connection is secured it uses wss port which returns an error
```
WebSocket connection to 'wss://backend.test:6001/app/app-key?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: An SSL error has occurred and a secure connection to the server cannot be made.
```
does anyone know how to make wss port work on valet and mac ?

**Comment by ahmadyousefdev** [comment]
The problem was with the PUSHER_HOST and PUSHER_PORT, you have to make a proxy while using valet

if anyone else needs to make secure websockets work with soketi and laravel valet, I wrote this tutorial that might be useful https://ahmadyousef.me/blog/11
