### ISSUE TITLE
Has anyone managed to run Soketi on FreeBSD?

### ISSUE THREAD

**Issue by Piecio** [soketi/pws#1148]
Has anyone managed to run soketi on FreeBSD? (Node 18.19.1, npm 10.5.0)

**I run the server application with the command:** 

`soketi start `

**and I  get the error:**

`/usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws.js:22
                throw new Error('This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).\n\n' + e.toString());
                ^

Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: Cannot find module './uws_freebsd_x64_108.node'
Require stack:
- /usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws.js
- /usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/dist/server.js
- /usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/dist/index.js
- /usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/dist/cli/cli.js
- /usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/dist/cli/index.js
- /usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/bin/server.js
    at /usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/usr/home/dobrys/.npm-global/lib/node_modules/@soketi/soketi/dist/server.js:18:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)`

There is no 'uws_freebsd_x64_108.node' file in node_modules/@soketi/soketi/node_modules/uWebSockets.js directory:
![image](https://github.com/soketi/soketi/assets/4405359/a00399fd-80e0-4505-9d9f-74e6a838365e)

**Comment by LemarinelNet** [comment]
Hi, 
Not sure if this will help, but I had this message when I installed soketi with Node 20.
After having installed nvm and node 18, soketi does start on Macbook M3.

**Comment by Piecio** [comment]
> Hi, 
> Not sure if this will help, but I had this message when I installed soketi with Node 20.
> After having installed nvm and node 18, soketi does start on Macbook M3.

Hi,
Thanks for reply. On Freebsd and Node 18 - still the same error..

**Comment by SerJaimeLannister** [comment]
I think this can go to uwebsockets.js issue though I am not sure.
