### ISSUE TITLE
Unable to use in Kubernetes

### ISSUE THREAD

**Issue by HelloChrisBrown** [soketi/pws#85]
I first tried to deploy the helm chart and get an error that version 2.2.0 does not exist. 

I then tried to test by running a container individually and am still getting an error. Am I missing something?

```
kubectl run -i --rm --tty debug --image=quay.io/soketi/pws:0.8-16-alpine -- sh    
```

```   
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: Internal error occurred: error attaching to container: container not running (166086ad6351e1ddd044f69aecf4166d6e20e923b48c100f5a9e385f4710f6fc)
/app/node_modules/prom-client/lib/metric.js:36
			throw new Error('Invalid metric name');
			      ^

Error: Invalid metric name
    at new Metric (/app/node_modules/prom-client/lib/metric.js:36:10)
    at new Gauge (/app/node_modules/prom-client/lib/gauge.js:19:1)
    at PrometheusMetricsDriver.registerMetrics (/app/dist/metrics/prometheus-metrics-driver.js:65:31)
    at new PrometheusMetricsDriver (/app/dist/metrics/prometheus-metrics-driver.js:12:14)
    at new Metrics (/app/dist/metrics/metrics.js:10:27)
    at Server.start (/app/dist/server.js:165:31)
    at Cli.start (/app/dist/cli/cli.js:109:28)
    at Function.start (/app/dist/cli/cli.js:97:26)
    at /app/dist/cli/index.js:6:63
    at M.applyBuilderUpdateUsageAndParse (/app/node_modules/yargs/build/index.cjs:1:7359)
pod "debug" deleted
```

**Comment by HelloChrisBrown** [comment]
@sergk8668 That did it. Thanks!

**Comment by rennokki** [comment]
Thanks for figuring it out. [I have pushed the changes](https://github.com/soketi/charts/commit/ffc13056ff9acdd2fb789a6667789ce1e0d0c6d8) in chart version 0.2.1.

- Replaced `/health` and `/ready` with `/` as you have indicated.
- Forced port `6001` for pods. This is ok to be forced because you may change the port in the `service.port` field in `values.yaml`.
- I have fixed the liveness/readiness probes for network-watcher as it was an issue here too.
